<html>
<head>
<title>TestNG:  My Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>My Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>20/9/0</td>
</tr><tr>
<td>Started on:</td><td>Tue Mar 07 18:09:10 AST 2023</td>
</tr>
<tr><td>Total time:</td><td>152 seconds (152018 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.EditExpenseCategory()'><b>EditExpenseCategory</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td><div><pre>java.lang.AssertionError: ::Item not updated expected [�
Alert!
Category Updated Successfully] but found [×
Alert!
Category Updated Successfully]
	at testCases.ExpenseCategoryTestCases.EditExpenseCategory(ExpenseCategoryTestCases.java:92)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace129296335", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace129296335'><pre>java.lang.AssertionError: ::Item not updated expected [�
Alert!
Category Updated Successfully] but found [×
Alert!
Category Updated Successfully]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.ExpenseCategoryTestCases.EditExpenseCategory(ExpenseCategoryTestCases.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>3</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.deleteExpenseCategory()'><b>deleteExpenseCategory</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td><div><pre>java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
	at org.openqa.selenium.internal.Require$ArgumentChecker.nonNull(Require.java:204)
	at org.openqa.selenium.By$ByXPath.&lt;init&gt;(By.java:287)
	at org.openqa.selenium.By.xpath(By.java:89)
	at elementRepository.ExpenseCategory.deleteItem(ExpenseCategory.java:183)
	at testCases.ExpenseCategoryTestCases.deleteExpenseCategory(ExpenseCategoryTestCases.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace235240728", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace235240728'><pre>java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
	at org.openqa.selenium.internal.Require$ArgumentChecker.nonNull(Require.java:204)
	at org.openqa.selenium.By$ByXPath.&lt;init&gt;(By.java:287)
	at org.openqa.selenium.By.xpath(By.java:89)
	at elementRepository.ExpenseCategory.deleteItem(ExpenseCategory.java:183)
	at testCases.ExpenseCategoryTestCases.deleteExpenseCategory(ExpenseCategoryTestCases.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>3</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.searchExpenseCategory()'><b>searchExpenseCategory</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td><div><pre>java.lang.AssertionError: ::Search is working expected [orange] but found [.........RESULT NOT FOUND.......]
	at testCases.ExpenseCategoryTestCases.searchExpenseCategory(ExpenseCategoryTestCases.java:59)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace940462640", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace940462640'><pre>java.lang.AssertionError: ::Search is working expected [orange] but found [.........RESULT NOT FOUND.......]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.ExpenseCategoryTestCases.searchExpenseCategory(ExpenseCategoryTestCases.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>2</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.ManageExpensesTestCases.verifyAddNewExpenseRecord()'><b>verifyAddNewExpenseRecord</b><br>Test class: testCases.ManageExpensesTestCases</td>
<td><div><pre>java.lang.AssertionError: ::Expense record created expected [�
Alert!
Expense Record Created Successfully] but found [×
Alert!
Expense Record Created Successfully]
	at testCases.ManageExpensesTestCases.verifyAddNewExpenseRecord(ManageExpensesTestCases.java:90)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1952359060", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1952359060'><pre>java.lang.AssertionError: ::Expense record created expected [�
Alert!
Expense Record Created Successfully] but found [×
Alert!
Expense Record Created Successfully]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.ManageExpensesTestCases.verifyAddNewExpenseRecord(ManageExpensesTestCases.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>7</td>
<td>testCases.ManageExpensesTestCases@1eb5174b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForInValidUser()'><b>verifyLoginForInValidUser</b><br>Test class: testCases.LoginTestCases</td>
<td><div><pre>java.lang.AssertionError: Alert same as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at testCases.LoginTestCases.verifyLoginForInValidUser(LoginTestCases.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1958256044", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1958256044'><pre>java.lang.AssertionError: Alert same as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.LoginTestCases.verifyLoginForInValidUser(LoginTestCases.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>1</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider()'><b>verifyLoginForInValidUserwithExcelDataProvider</b><br>Test class: testCases.LoginTestCases<br>Parameters: asdf, pppp</td>
<td><div><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1866314849", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1866314849'><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider()'><b>verifyLoginForInValidUserwithExcelDataProvider</b><br>Test class: testCases.LoginTestCases<br>Parameters: neena, neena</td>
<td><div><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace964879363", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace964879363'><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider()'><b>verifyLoginForInValidUserwithExcelDataProvider</b><br>Test class: testCases.LoginTestCases<br>Parameters: hana, hana</td>
<td><div><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1493055255", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1493055255'><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider()'><b>verifyLoginForInValidUserwithExcelDataProvider</b><br>Test class: testCases.LoginTestCases<br>Parameters: $yamala, 12@1234</td>
<td><div><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace943243320", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace943243320'><pre>java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></div></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.addNewExpenseCategory()'><b>addNewExpenseCategory</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td></td>
<td>3</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.ManageExpensesTestCases.verifyAddExpenseFieldsPresence()'><b>verifyAddExpenseFieldsPresence</b><br>Test class: testCases.ManageExpensesTestCases</td>
<td></td>
<td>4</td>
<td>testCases.ManageExpensesTestCases@1eb5174b</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyAddNewProductPageDefaultCheckboxValuesSelected()'><b>verifyAddNewProductPageDefaultCheckboxValuesSelected</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>3</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyAddNewProductPageDefaultRadioButtonValues()'><b>verifyAddNewProductPageDefaultRadioButtonValues</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>3</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyCheckBox()'><b>verifyCheckBox</b><br>Test class: testCases.LoginTestCases</td>
<td></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.verifyExpenseCategoryPageIsLoaded()'><b>verifyExpenseCategoryPageIsLoaded</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.HomePageTestCases.verifyHomePageTitle()'><b>verifyHomePageTitle</b><br>Test class: testCases.HomePageTestCases</td>
<td></td>
<td>1</td>
<td>testCases.HomePageTestCases@c333c60</td></tr>
<tr>
<td title='testCases.HomePageTestCases.verifyHomePageURL()'><b>verifyHomePageURL</b><br>Test class: testCases.HomePageTestCases</td>
<td></td>
<td>1</td>
<td>testCases.HomePageTestCases@c333c60</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifyLoginForValidUser()'><b>verifyLoginForValidUser</b><br>Test class: testCases.LoginTestCases</td>
<td></td>
<td>1</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.ManageExpensesTestCases.verifyManageExpensePageLoad()'><b>verifyManageExpensePageLoad</b><br>Test class: testCases.ManageExpensesTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageExpensesTestCases@1eb5174b</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyManageProductPageisLoaded()'><b>verifyManageProductPageisLoaded</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>3</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyManageProductTitle()'><b>verifyManageProductTitle</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyManageProductURL()'><b>verifyManageProductURL</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.ExpenseCategoryTestCases.verifyNewSearchResetButtonColors()'><b>verifyNewSearchResetButtonColors</b><br>Test class: testCases.ExpenseCategoryTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ExpenseCategoryTestCases@79da8dc5</td></tr>
<tr>
<td title='testCases.ManageExpensesTestCases.verifyNewSearchResetButtonFontColor()'><b>verifyNewSearchResetButtonFontColor</b><br>Test class: testCases.ManageExpensesTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageExpensesTestCases@1eb5174b</td></tr>
<tr>
<td title='testCases.ManageExpensesTestCases.verifyNewSearchResetButtonFontSize()'><b>verifyNewSearchResetButtonFontSize</b><br>Test class: testCases.ManageExpensesTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageExpensesTestCases@1eb5174b</td></tr>
<tr>
<td title='testCases.ManageProductTestCases.verifyProductSearchPageLoad()'><b>verifyProductSearchPageLoad</b><br>Test class: testCases.ManageProductTestCases</td>
<td></td>
<td>2</td>
<td>testCases.ManageProductTestCases@67080771</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifySignInButtonColor()'><b>verifySignInButtonColor</b><br>Test class: testCases.LoginTestCases</td>
<td></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.LoginTestCases.verifySignInButtonText()'><b>verifySignInButtonText</b><br>Test class: testCases.LoginTestCases</td>
<td></td>
<td>0</td>
<td>testCases.LoginTestCases@11bd0f3b</td></tr>
<tr>
<td title='testCases.HomePageTestCases.verifyUserLogout()'><b>verifyUserLogout</b><br>Test class: testCases.HomePageTestCases</td>
<td></td>
<td>2</td>
<td>testCases.HomePageTestCases@c333c60</td></tr>
</table><p>
</body>
</html>